server:
  port: 9010
spring:
  application:
    name: gateway-server  #全部小写

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
